// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("+2fnBN8hnXy4/zdd");
export default defineConfig({
  generate: {
    async run(snaplet) {
      await snaplet.$pipe([
        snaplet.workspace_user_type((x) => x(2, (index) => ({
          type:["admin", "user"][index],
        }))),
        snaplet.users((x) => x(20)),
        snaplet.workspace((x) => x(3, () => ({
          channel: (x) => x({min: 1, max: 3}, () => ({
            channel_member: (x) => x({min: 1, max: 3}),
            channel_thread: (x) => x({min: 1, max: 3}, () => ({
              channel_thread_message: (x) => x({min: 1, max: 3}),
            })),
          })),
          workspace_member: (x) => x({min: 1, max: 3}),
        })), {autoConnect: true}),
      ])
    },
  },
});